# Get editor completions based on the config schema
# "$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true


# Replace the "â¯" symbol in the prompt with "âœ"
# The name of the module we are configuring is "character"
[character] 
# The "success_symbol" segment is being set to "âœ" with the color "bold green"
success_symbol = "[âœ](bold green)"

# Battery
[[battery.display]]
threshold = 10
style = "bold red"

[[battery.display]] # "bold red" style and discharging_symbol when capacity is between 0% and 10%
threshold = 30
style = "bold red"
discharging_symbol = "ğŸ˜‘"

[[battery.display]] # "bold red" style and discharging_symbol when capacity is between 0% and 10%
threshold = 50
style = "bold red"
discharging_symbol = "ğŸ˜"

[[battery.display]] # "bold yellow" style and ğŸ’¦ symbol when capacity is between 10% and 30%
threshold = 100
style = "bold green"
discharging_symbol = "ğŸ˜ƒ"

# when capacity is over 30%, the battery indicator will not be displayed


[battery]
full_symbol = "ğŸ˜ƒ "
charging_symbol = "ğŸ¤© "
discharging_symbol = "ğŸ’€ "

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true
